//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStoreMySQL.Model {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class mySQLSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static mySQLSettings defaultInstance = ((mySQLSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new mySQLSettings())));
        
        public static mySQLSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost; Port=3306; Database=mydb; Uid=root; Pwd=6ponkii6lici; pooling=t" +
            "rue")]
        public string MYSQL_URI {
            get {
                return ((string)(this["MYSQL_URI"]));
            }
            set {
                this["MYSQL_URI"] = value;
            }
        }
    }
}
